spring:
    application:
        name: anime-service
    threads:
        virtual:
            enabled: true

logging:
    level:
        academy.devdojo: DEBUG

server:
    servlet:
        context-path: /anime-service
    error:
        include-message: never
    tomcat:
        threads:
            max: 20

